run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck      # Error handling kontrolü
    - gosimple      # Simplification önerileri
    - govet         # Go vet
    - ineffassign   # Kullanılmayan atamalar
    - staticcheck   # Static analysis
    - unused        # Kullanılmayan kod
    - gofmt         # Format kontrolü
    - goimports     # Import sıralaması
    - misspell      # Yazım hataları
    - gocritic      # Kod kritikleri
    - revive        # golint yerine
    - gosec         # Güvenlik kontrolü

linters-settings:
  govet:
    check-shadowing: true

  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-rules:
    # Test dosyalarında bazı kuralları gevşet
    - path: _test\.go
      linters:
        - gosec
        - gocritic

version: "2"